meta:
  engine: 4.0.4
  name: samoklava
  version: 0.3
  author: soundmonster
  url: https://github.com/soundmonster/samoklava
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      key.padding: ky
      columns:
        pinky:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_pinky
        ring:
          key:
            stagger: 0.7 ky
            spread: kx
            column_net: col_ring
        middle:
          key:
            stagger: 0.2 ky
            spread: kx
            column_net: col_middle
        index:
          key:
            stagger: -0.2 ky
            spread: kx
            column_net: col_index
        inner:
          key:
            stagger: -0.1 ky
            spread: kx
            column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.5 kx, -1 ky]
      columns:
        near:
          rows.upperThumb.skip: true
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_middle
        home:
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_index
        far:
          rows.upperThumb.skip: true
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_inner
      rows:
        lowerThumb:
        upperThumb:
          row_net: row_thumb
        
 
outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + px, ky + py]
      corner: px
  thumbfan_glue:
    - what: polygon
      points:
        - ref: matrix_inner_bottom
          shift: [0.5 kx + 0.5px, -0.5 ky + 0.5 py]
        - ref: thumbfan_far_lowerThumb
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: thumbfan_far_lowerThumb
          shift: [0.5 kx - 0.5px, -0.5 ky - 0.5 py]
        - ref: thumbfan_near_lowerThumb
          shift: [-0.5 kx + 0.5 px, -0.5 ky - 0.5 py]
        - ref: matrix_pinky_bottom
          shift: [0.5 kx - 0.5 py, -0.5 ky - 0.5 py]
        - ref: matrix_pinky_home
        - ref: matrix_inner_home
  patch_outer:
    - what: polygon
      points:
        - ref: matrix_ring_top
        - ref: matrix_ring_bottom
        - ref: matrix_pinky_bottom
          shift: [-0.5 (kx + px), 0]
        - ref: matrix_pinky_top
          shift: [-0.5 (kx + px), 0]
  patch_inner:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5 (kx + px), 0]
        - ref: matrix_inner_bottom
          shift: [0.5 (kx + px), 0]
        - ref: matrix_index_bottom
        - ref: matrix_index_top
  controller_area:
    - what: rectangle
      where:
        - ref: matrix_inner_top
          # re-tranalte to new anchor position
          shift: [32/2 + 0 kx, 76.5/2 - 4.05 ky]
      size: [32, 76.5]
      corner: px
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
      corner: 1
  keywell:
    - "raw"
    - "+patch_inner"
    - "+patch_outer"
    - "+thumbfan_glue"
  base_outline:
    - "keywell"
    - "+controller_area"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_ring_home
          shift: [-0.5 kx, 0 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_pinky_bottom
          shift: [0.5 kx, 0]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner_top
          shift: [-0.5 kx, 0]
      radius: 1.05
    palm:
      what: circle
      where:
        - ref: matrix_index_bottom
          shift: [0, -1.06 ky]
      radius: 1.05
    upperThumb:
      what: circle
      where:
        - ref: thumbfan_far_lowerThumb
          shift: [-0.55 kx, 0]
      radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 2.05
    bottom_left:
      radius: 2.05
    top_right:
      radius: 2.05
    palm:
      radius: 2.05
    upperThumb:
      radius: 2.05
  bottom_outline:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-screw_holes"
  plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"
  pcb:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-mounting_holes"
